### PR TITLE
Update ansible syntax

### LINKED ISSUE #38: Update ansible syntax
As of ansible 2.16 the deprecated include module will be removed.
See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_module.html

The role should be updated before ansible is reaching this version.

It is also recommended to use FQNC for all modules.

### PR DESCRIPTION
**Pull request by FrankGiesecke**
Closes #38

### CODE REVIEW

**Comment by trombik** [comment]
thanks. as i'm in the process to update our local package repository, i cannot perform the tests until the process finishes, which takes a few days.

**Comment by trombik** [comment]
sorry for the delay. I'm working on another PR with your fixes.

**Comment by FrankGiesecke** [comment]
@trombik Thank you for your feedback. I'm looking forward for your approval.

**Comment by trombik** [comment]
merged. would you test the `master`? it's backward-compatible unless you are a CentOS user.

**Pull request merged**
